action/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.message, name='home'),
    path('<int:pk>/edit/', views.RateUpdateView.as_view(), name='rate_edit'),
]

config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('i18n', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path(r'admin/', admin.site.urls),
    path('', include('action.urls')),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

action/models.py
from django.core.validators import FileExtensionValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone
from phone_field import PhoneField


class Message(models.Model):
    name = models.CharField(max_length=200)
    phone_number = PhoneField(blank=False)

    def __str__(self):
        return self.name


class Videos(models.Model):
    video = models.FileField(upload_to='videos_uploaded', null=True, validators=[FileExtensionValidator( allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])
    date_uploaded = models.DateTimeField(default=timezone.now)
    title = models.CharField(max_length=100)
    caption = models.CharField(max_length=200)

    class Meta:
        verbose_name = 'video'
        verbose_name_plural = 'videos'

    def __str__(self):
        return self.title


class DescRate(models.Model):
    tasks = models.CharField(max_length=200)

    def __str__(self):
        return self.tasks


class Rate(models.Model):
    title = models.CharField(max_length=100)
    first = models.CharField(max_length=100, null=True, blank=True)
    second = models.CharField(max_length=100, null=True, blank=True)
    third = models.CharField(max_length=100, null=True, blank=True)
    prize = models.CharField(max_length=20)
    descs = models.ManyToManyField(DescRate)

    class Meta:
        db_table = 'rate'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('rate_detail', args=[str(self.pk)])

action/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
import requests
from bs4 import BeautifulSoup
from django.urls import reverse_lazy
from action.models import Message, Videos, Rate
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
import telebot
from termcolor import colored
token = '2142956792:AAHsITOmzE4iDafHHjZdyQxmd6Mb30SodA4'
bot = telebot.TeleBot(token)
chat_id = '5139402876'


def home():
    DOLLAR_RUB = 'https://nbu.uz/uz/exchange-rates/'
    headers = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36'}
    full_page = requests.get(DOLLAR_RUB, headers)
    soup = BeautifulSoup(full_page.content, 'html.parser')
    a = soup.findAll('a', {'href': '/uz/exchange-rates/', }, 'span')
    r = soup.findAll('td')
    r = str(r)
    r = r[574:580]
    e = a[4].text
    a = a[1].text
    a = a[6:]
    e = e[6:]
    c = [a, e, r]
    return c


def message(request):
    rate = Rate.objects.all()
    a = home()

    if request.method == 'POST':
        UserName = request.POST.get('name')
        UserNumber = request.POST.get('number')
        SaveValue = Message()
        SaveValue.name = UserName
        SaveValue.phone_number = UserNumber
        print(UserName, UserNumber)
        SaveValue.save()
        sms = f"Username:  {UserName}\n\nUserNUmber:  {UserNumber}"
        try:
            bot.send_message(chat_id, sms)
        except:
            HttpResponse('Try again')
    context = {
        'a': a[0],
        'e': a[1],
        'r': a[2],
        'rates': rate,
    }

    return render(request, 'index.html', context)


class RateUpdateView(UpdateView):
    model = Rate
    template_name = 'rate/rate_edit.html'
    fields = ['title', 'first', 'second', 'third', 'prize']
    success_url = reverse_lazy('home')

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {%block title %}Home Page{% endblock %}
</head>
<body>
    <h1 style="text-align:center">Hi everyone</h1>
    {{a}}
    <br>
    <br>
    <br>
    {% for rate in rate_list %}
    {{rate.title}}
    <ul>
        <li> {{rate.first}}</li>
        <li>{{rate.second}}</li>
        <li> {{rate.third}}</li>
    </ul>
    {{rate.prize}}
    {% endfor %}

        {% for video in videos %}
            <video width="500" height="500" controls >
                <source src="{{video.video.url}}" type="video/mp4">
            </video>
            <b>{{video.title}}</b>
            <h2>{{video.caption}}</h2>
            <h2>{{video.date_uploaded}}</h2>
        {% endfor %}
    <a href="{}"></a>
    <form method="POST">
        {% csrf_token %}
        <label>
            <input type="text" name="name" placeholder="Your Name...">
        </label>
        <label>
            <input type="tel" name="number" placeholder="+998" >
        </label>
        <button type="submit">Send Message</button>
    </form>
</body>
</html>

templates/rate/rate_edit.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <title>{{rate.title}}</title>
</head>
<body>
    <div class="container">
    <h1 class="text-center mt-5">Update</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mt-2">Save</button>
    </form>
    </div>
</body>
</html>

templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <form action="" method="POST">{% csrf_token %}

    <input type="text" name="title" placeholder="Enter Video Title here"><br>
    <input type="file" name="video" accept="video/*">
    <button type="submit"> Upload New Video </button>
</form>

</body>
</html>